#!/usr/bin/env python
import click

import skbio


@click.group()
def cli():
    pass

@cli.group()
def silva():
    pass

@silva.command("extract-fungi")
@click.argument("fasta_fp")
@click.argument("accession_fp")
@click.argument("taxonomy_fp")
@click.argument("output_fp")
def extract_fungi(fasta_fp, accession_fp, taxonomy_fp, output_fp):
    try:
        fasta_fh = open(fasta_fp, "U")
        accession_fh = open(accession_fp, "U")
        taxonomy_fh = open(taxonomy_fp, "U")
        skbio.write(fungi_from_fasta(fasta_fh, accession_fh, taxonomy_fh), into=output_fp, format="fasta")
    finally:
        fasta_fh.close()
        accession_fh.close()
        taxonomy_fh.close()


if __name__ == "__main__":
    cli()
