#!/usr/bin/env python
import click

import skbio

from ghosttree.silva.filter import fungi_from_fasta


@click.group()
def cli():
    pass

@cli.group()
def silva():
    pass

@silva.command("extract-fungi")
@click.argument("fasta-file", type=click.File("U"))
@click.argument("accession-file", type=click.File("U"))
@click.argument("taxonomy-file", type=click.File("U"))
@click.argument("output-file", type=click.File("w"))
def extract_fungi(fasta_file, accession_file, taxonomy_file, output_file):
    skbio.write(fungi_from_fasta(fasta_file, accession_file, taxonomy_file), into=output_file, format="fasta")


if __name__ == "__main__":
    cli()
